#!/bin/sh
nvidia-docker run -it -p 8888:8888 --volume "$PWD:/home/jovyan" \
	--env GOOGLE_CLOUD_STORAGE_BUCKET=$GOOGLE_CLOUD_STORAGE_BUCKET \
	--env GOOGLE_SERVICE_ACCOUNT_JSON_PATH=$GOOGLE_SERVICE_ACCOUNT_JSON_PATH \
	--env JUPYTER_PASSWORD_HASH=$JUPYTER_PASSWORD_HASH \
	--env SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL \
	--env GOOGLE_STACKDRIVER_URL=$GOOGLE_STACKDRIVER_URL \
	--env SLACK_NOTIFY_RECIEVE_USER=$SLACK_NOTIFY_RECIEVE_USER \
	-t dogwood008/deepfx
